Set hostname, fix few bugs and add support for additional DHCP options

diff --git a/recipes-core/images/files/init b/recipes-core/images/files/init
--- a/recipes-core/images/files/init
+++ b/recipes-core/images/files/init
@@ -92,7 +92,7 @@ fi
 if [ -n "${network}" ]; then
 	if [ -z "${interface}" ]; then
 		echo -n "Fail to retrieve interface! "
-		do_umount_reboot
+		do_reboot
 	fi
 
 	ip link set "${interface}" up
@@ -108,15 +108,22 @@ if [ -n "${network}" ]; then
 	done
 
 	if [ "${autoconf}" = "dhcp" ]; then
-		eval $(udhcpc -n -q -i ${interface} -O rootpath -O usrpath -s /etc/udhcpc.d/60elettra 2>/dev/null)
+		eval $(udhcpc -n -q -i ${interface} -O rootpath -O usrpath -O runtimepath -O homepath -s /etc/udhcpc.d/60elettra 2>/dev/null)
 	fi
 
 	ip addr add ${ip}/${mask} dev ${interface}
 	if [ "$?" -ne 0 ]; then
 		echo -n "Fail to configure interface! "
-		do_umount_reboot
+		do_reboot
 	fi
 	ip route add default via ${router} dev ${interface}
+fi
+
+# Set hostname
+if [ -z "$hostname" ]; then
+	hostname localhost
+else
+	hostname $(echo $hostname | cut -d"." -f1)
 fi
 
 # Drop into a shell...
@@ -152,10 +159,10 @@ case $rootfstype in
 esac
 if [ "$?" -ne 0 ]; then
 	echo -n "Fail to mount root(path)! "
-	do_umount_reboot
+	do_reboot
 fi
 
-# Mount usrpath (if necessary)...
+# Mount usrpath...
 case $usrfstype in
 	nfs)	mount -t ${usrfstype} ${siaddr}:${usrpath} /mnt/rootfs/usr -o nfsvers=4,${usrflags},ro,nolock;;
 	*)	mount -t ${usrfstype} /mnt/rootfs/${usrpath} /mnt/rootfs/usr -o ${usrflags},ro,bind;;
@@ -164,6 +171,26 @@ if [ "$?" -ne 0 ]; then
 	echo -n "Fail to mount usr(path)! "
 	do_reboot
 fi
+
+#### Mount homepath...
+###case $rootfstype in
+###	nfs)	mount -t ${rootfstype} ${siaddr}:${homepath} /mnt/rootfs/home -o nfsvers=4,${rootflags},rw,nolock;;
+###esac
+###if [ "$?" -ne 0 ]; then
+###	echo -n "Fail to mount home(path)! "
+###	do_reboot
+###fi
+###
+#### Mount runtimepath...
+###case $rootfstype in
+###	nfs)	mount -t ${rootfstype} ${siaddr}:${runtimepath} /mnt/rootfs/runtime -o nfsvers=4,${rootflags},ro,nolock;;
+###esac
+###if [ "$?" -ne 0 ]; then
+###	echo -n "Fail to mount runtime(path)! "
+###	do_reboot
+###fi
+###
+###mount -t ${rootfstype} ${siaddr}:${runtimepath}/site/`hostname -s` /mnt/rootfs/runtime/site/`hostname -s` -o nfsvers=4,${rootflags},rw,nolock 1>/dev/null 2>&1
 
 # Remount usrpath
 case `sed -n 's,VARIANT_ID=".*-\(.*\)",\1,p' /mnt/rootfs/etc/os-release` in
